osx_image: xcode7.3
language: generic
matrix:
  include:
    - os: osx
      env: NIMBLE_RUNTIME_IOS_SDK_VERSION=9.0 TYPE=ios
    - os: osx
      env: NIMBLE_RUNTIME_OSX_SDK_VERSION=10.10 TYPE=osx
    - os: osx
      env: TYPE=swiftpm
    - os: linux
      dist: trusty
      sudo: required
      env: TYPE=swiftpm
install:
  - if [[ "$TYPE" == "swiftpm" ]]; then eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"; fi
script:
  - ./test $TYPE
