branches:
  only:
    - master

language: generic
jobs:
  include:
    # - &xcode
    #   name: Xcode 10.3 / Swift 5.0
    #   os: osx
    #   osx_image: xcode10.3
    #   script:
    #     - ./test macos
    #     - ./test ios
    #     - ./test tvos
    # - &swiftpm_darwin
    #   name: SwiftPM / Darwin / Swift 5.0
    #   os: osx
    #   osx_image: xcode10.3
    #   script: ./test swiftpm
    - &swiftpm_linux
      name: SwiftPM / Linux / Swift 5.3 Development
      os: linux
      env:
        - SWIFT_VERSION=5.3-DEVELOPMENT-SNAPSHOT-2020-09-04-a
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - ./test swiftpm
    - <<: *swiftpm_linux
      name: SwiftPM / Linux / Swift Development
      env:
        - SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2020-08-31-a
install: true
script:
  - ./test $TYPE

notifications:
  email: false
