osx_image: xcode7.2
language: generic
matrix:
  include:
    - os: osx
      env: NIMBLE_RUNTIME_IOS_SDK_VERSION=9.0 TYPE=ios
    - os: osx
      env: NIMBLE_RUNTIME_OSX_SDK_VERSION=10.10 TYPE=osx
    - os: linux
      dist: trusty
      sudo: required
      env: TYPE=swiftpm
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./script/travis-install-linux; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . ~/.swiftenv/init; fi
  - ./test $TYPE
