#if !canImport(ObjectiveC)
import XCTest

extension AllPassTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AllPassTest = [
        ("testAllPassArray", testAllPassArray),
        ("testAllPassCollectionsWithOptionalsDontWork", testAllPassCollectionsWithOptionalsDontWork),
        ("testAllPassCollectionsWithOptionalsUnwrappingOneOptionalLayer", testAllPassCollectionsWithOptionalsUnwrappingOneOptionalLayer),
        ("testAllPassMatcher", testAllPassMatcher),
        ("testAllPassSet", testAllPassSet),
        ("testAllPassWithNilAsExpectedValue", testAllPassWithNilAsExpectedValue),
    ]
}

extension AsyncTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AsyncTest = [
        ("testCombiningAsyncWaitUntilAndToEventuallyIsNotAllowed", testCombiningAsyncWaitUntilAndToEventuallyIsNotAllowed),
        ("testSubjectUnderTestIsReleasedFromMemory", testSubjectUnderTestIsReleasedFromMemory),
        ("testToEventuallyMustBeInMainThread", testToEventuallyMustBeInMainThread),
        ("testToEventuallyNegativeMatches", testToEventuallyNegativeMatches),
        ("testToEventuallyPositiveMatches", testToEventuallyPositiveMatches),
        ("testToEventuallyWithCustomDefaultTimeout", testToEventuallyWithCustomDefaultTimeout),
        ("testWaitUntilDetectsStalledMainThreadActivity", testWaitUntilDetectsStalledMainThreadActivity),
        ("testWaitUntilErrorsIfDoneIsCalledMultipleTimes", testWaitUntilErrorsIfDoneIsCalledMultipleTimes),
        ("testWaitUntilMustBeInMainThread", testWaitUntilMustBeInMainThread),
        ("testWaitUntilNegativeMatches", testWaitUntilNegativeMatches),
        ("testWaitUntilPositiveMatches", testWaitUntilPositiveMatches),
        ("testWaitUntilTimesOutIfNotCalled", testWaitUntilTimesOutIfNotCalled),
        ("testWaitUntilTimesOutWhenExceedingItsTime", testWaitUntilTimesOutWhenExceedingItsTime),
        ("testWaitUntilWithCustomDefaultsTimeout", testWaitUntilWithCustomDefaultsTimeout),
    ]
}

extension BeAKindOfObjCTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeAKindOfObjCTest = [
        ("testFailureMessages", testFailureMessages),
        ("testPositiveMatch", testPositiveMatch),
    ]
}

extension BeAKindOfSwiftTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeAKindOfSwiftTest = [
        ("testFailureMessages", testFailureMessages),
        ("testPositiveMatch", testPositiveMatch),
    ]
}

extension BeAnInstanceOfTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeAnInstanceOfTest = [
        ("testFailureMessages", testFailureMessages),
        ("testFailureMessagesSwiftTypes", testFailureMessagesSwiftTypes),
        ("testPositiveMatch", testPositiveMatch),
        ("testPositiveMatchSwiftTypes", testPositiveMatchSwiftTypes),
    ]
}

extension BeCloseToTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeCloseToTest = [
        ("testBeCloseTo", testBeCloseTo),
        ("testBeCloseToArray", testBeCloseToArray),
        ("testBeCloseToOperator", testBeCloseToOperator),
        ("testBeCloseToOperatorWithDate", testBeCloseToOperatorWithDate),
        ("testBeCloseToWithCGFloat", testBeCloseToWithCGFloat),
        ("testBeCloseToWithDate", testBeCloseToWithDate),
        ("testBeCloseToWithin", testBeCloseToWithin),
        ("testBeCloseToWithinOperator", testBeCloseToWithinOperator),
        ("testBeCloseToWithinOperatorWithDate", testBeCloseToWithinOperatorWithDate),
        ("testBeCloseToWithNSDate", testBeCloseToWithNSDate),
        ("testBeCloseToWithNSNumber", testBeCloseToWithNSNumber),
        ("testPlusMinusOperator", testPlusMinusOperator),
        ("testPlusMinusOperatorWithDate", testPlusMinusOperatorWithDate),
    ]
}

extension BeEmptyTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeEmptyTest = [
        ("testBeEmptyNegative", testBeEmptyNegative),
        ("testBeEmptyPositive", testBeEmptyPositive),
        ("testNilMatches", testNilMatches),
    ]
}

extension BeFalseTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeFalseTest = [
        ("testShouldMatchFalse", testShouldMatchFalse),
        ("testShouldNotMatchNilBools", testShouldNotMatchNilBools),
        ("testShouldNotMatchTrue", testShouldNotMatchTrue),
    ]
}

extension BeFalsyTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeFalsyTest = [
        ("testShouldMatchFalse", testShouldMatchFalse),
        ("testShouldMatchNilBools", testShouldMatchNilBools),
        ("testShouldMatchNilTypes", testShouldMatchNilTypes),
        ("testShouldNotMatchNonNilTypes", testShouldNotMatchNonNilTypes),
        ("testShouldNotMatchTrue", testShouldNotMatchTrue),
    ]
}

extension BeGreaterThanOrEqualToTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeGreaterThanOrEqualToTest = [
        ("testGreaterThanOrEqualTo", testGreaterThanOrEqualTo),
        ("testGreaterThanOrEqualToOperator", testGreaterThanOrEqualToOperator),
    ]
}

extension BeGreaterThanTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeGreaterThanTest = [
        ("testGreaterThan", testGreaterThan),
        ("testGreaterThanOperator", testGreaterThanOperator),
    ]
}

extension BeIdenticalToObjectTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeIdenticalToObjectTest = [
        ("testBeIdenticalToNegative", testBeIdenticalToNegative),
        ("testBeIdenticalToNegativeMessage", testBeIdenticalToNegativeMessage),
        ("testBeIdenticalToPositive", testBeIdenticalToPositive),
        ("testBeIdenticalToPositiveMessage", testBeIdenticalToPositiveMessage),
        ("testFailsOnNils", testFailsOnNils),
        ("testOperators", testOperators),
    ]
}

extension BeIdenticalToTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeIdenticalToTest = [
        ("testBeAlias", testBeAlias),
        ("testBeIdenticalToNegative", testBeIdenticalToNegative),
        ("testBeIdenticalToNegativeMessage", testBeIdenticalToNegativeMessage),
        ("testBeIdenticalToPositive", testBeIdenticalToPositive),
        ("testBeIdenticalToPositiveMessage", testBeIdenticalToPositiveMessage),
        ("testOperators", testOperators),
    ]
}

extension BeLessThanOrEqualToTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeLessThanOrEqualToTest = [
        ("testLessThanOrEqualTo", testLessThanOrEqualTo),
        ("testLessThanOrEqualToOperator", testLessThanOrEqualToOperator),
    ]
}

extension BeLessThanTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeLessThanTest = [
        ("testLessThan", testLessThan),
        ("testLessThanOperator", testLessThanOperator),
    ]
}

extension BeNilTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeNilTest = [
        ("testBeNil", testBeNil),
    ]
}

extension BeTrueTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeTrueTest = [
        ("testShouldMatchTrue", testShouldMatchTrue),
        ("testShouldNotMatchFalse", testShouldNotMatchFalse),
        ("testShouldNotMatchNilBools", testShouldNotMatchNilBools),
    ]
}

extension BeTruthyTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeTruthyTest = [
        ("testShouldMatchBoolConvertibleTypesThatConvertToTrue", testShouldMatchBoolConvertibleTypesThatConvertToTrue),
        ("testShouldMatchNonNilTypes", testShouldMatchNonNilTypes),
        ("testShouldMatchTrue", testShouldMatchTrue),
        ("testShouldNotMatchBoolConvertibleTypesThatConvertToFalse", testShouldNotMatchBoolConvertibleTypesThatConvertToFalse),
        ("testShouldNotMatchFalse", testShouldNotMatchFalse),
        ("testShouldNotMatchNilBools", testShouldNotMatchNilBools),
        ("testShouldNotMatchNilTypes", testShouldNotMatchNilTypes),
    ]
}

extension BeVoidTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeVoidTest = [
        ("testBeVoid", testBeVoid),
    ]
}

extension BeginWithTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeginWithTest = [
        ("testNegativeMatches", testNegativeMatches),
        ("testPositiveMatches", testPositiveMatches),
    ]
}

extension ContainElementSatisfyingTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContainElementSatisfyingTest = [
        ("testContainElementSatisfying", testContainElementSatisfying),
        ("testContainElementSatisfyingDefaultErrorMessage", testContainElementSatisfyingDefaultErrorMessage),
        ("testContainElementSatisfyingNegativeCase", testContainElementSatisfyingNegativeCase),
        ("testContainElementSatisfyingNegativeCaseDefaultErrorMessage", testContainElementSatisfyingNegativeCaseDefaultErrorMessage),
        ("testContainElementSatisfyingNegativeCaseSpecificErrorMessage", testContainElementSatisfyingNegativeCaseSpecificErrorMessage),
        ("testContainElementSatisfyingSpecificErrorMessage", testContainElementSatisfyingSpecificErrorMessage),
    ]
}

extension ContainTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContainTest = [
        ("testCollectionArguments", testCollectionArguments),
        ("testContainObjCSubstring", testContainObjCSubstring),
        ("testContainSequence", testContainSequence),
        ("testContainSequenceAndSetAlgebra", testContainSequenceAndSetAlgebra),
        ("testContainSetAlgebra", testContainSetAlgebra),
        ("testContainSubstring", testContainSubstring),
        ("testVariadicArguments", testVariadicArguments),
    ]
}

extension ElementsEqualTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ElementsEqualTest = [
        ("testElementsEqualDifferentSequenceTypes", testElementsEqualDifferentSequenceTypes),
        ("testSequenceElementsEquality", testSequenceElementsEquality),
        ("testSequenceElementsEqualityUsingPredicateClosure", testSequenceElementsEqualityUsingPredicateClosure),
    ]
}

extension EndWithTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EndWithTest = [
        ("testEndWithNegatives", testEndWithNegatives),
        ("testEndWithPositives", testEndWithPositives),
    ]
}

extension EqualTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EqualTest = [
        ("testArrayEquality", testArrayEquality),
        ("testArrayOfOptionalsEquality", testArrayOfOptionalsEquality),
        ("testDataEquality", testDataEquality),
        ("testDictionariesWithDifferentSequences", testDictionariesWithDifferentSequences),
        ("testDictionaryEquality", testDictionaryEquality),
        ("testDoesNotMatchNils", testDoesNotMatchNils),
        ("testEquality", testEquality),
        ("testNSObjectEquality", testNSObjectEquality),
        ("testOperatorEquality", testOperatorEquality),
        ("testOperatorEqualityWithArrays", testOperatorEqualityWithArrays),
        ("testOperatorEqualityWithDictionaries", testOperatorEqualityWithDictionaries),
        ("testOptionalEquality", testOptionalEquality),
        ("testSetEquality", testSetEquality),
    ]
}

extension HaveCountTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HaveCountTest = [
        ("testHaveCountForArray", testHaveCountForArray),
        ("testHaveCountForDictionary", testHaveCountForDictionary),
        ("testHaveCountForSet", testHaveCountForSet),
    ]
}

extension MatchErrorTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MatchErrorTest = [
        ("testDoesNotMatchNils", testDoesNotMatchNils),
        ("testMatchErrorNegative", testMatchErrorNegative),
        ("testMatchErrorPositive", testMatchErrorPositive),
        ("testMatchNegativeMessage", testMatchNegativeMessage),
        ("testMatchNSErrorNegative", testMatchNSErrorNegative),
        ("testMatchNSErrorPositive", testMatchNSErrorPositive),
        ("testMatchPositiveMessage", testMatchPositiveMessage),
    ]
}

extension MatchTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MatchTest = [
        ("testMatchNegative", testMatchNegative),
        ("testMatchNegativeMessage", testMatchNegativeMessage),
        ("testMatchNils", testMatchNils),
        ("testMatchPositive", testMatchPositive),
        ("testMatchPositiveMessage", testMatchPositiveMessage),
    ]
}

extension PostNotificationTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PostNotificationTest = [
        ("testFailsWhenNoNotificationsArePosted", testFailsWhenNoNotificationsArePosted),
        ("testFailsWhenNotificationWithWrongNameIsPosted", testFailsWhenNotificationWithWrongNameIsPosted),
        ("testFailsWhenNotificationWithWrongObjectIsPosted", testFailsWhenNotificationWithWrongObjectIsPosted),
        ("testPassesWhenAllExpectedNotificationsArePosted", testPassesWhenAllExpectedNotificationsArePosted),
        ("testPassesWhenExpectedNotificationEventuallyIsPosted", testPassesWhenExpectedNotificationEventuallyIsPosted),
        ("testPassesWhenExpectedNotificationIsPosted", testPassesWhenExpectedNotificationIsPosted),
        ("testPassesWhenNoNotificationsArePosted", testPassesWhenNoNotificationsArePosted),
    ]
}

extension SatisfyAllOfTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SatisfyAllOfTest = [
        ("testOperatorAnd", testOperatorAnd),
        ("testSatisfyAllOf", testSatisfyAllOf),
    ]
}

extension SatisfyAnyOfTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SatisfyAnyOfTest = [
        ("testOperatorOr", testOperatorOr),
        ("testSatisfyAnyOf", testSatisfyAnyOf),
    ]
}

extension SynchronousTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SynchronousTest = [
        ("testFailAlwaysFails", testFailAlwaysFails),
        ("testNotToMatchesLikeToNot", testNotToMatchesLikeToNot),
        ("testToMatchAgainstLazyProperties", testToMatchAgainstLazyProperties),
        ("testToMatchesIfMatcherReturnsTrue", testToMatchesIfMatcherReturnsTrue),
        ("testToNegativeMatches", testToNegativeMatches),
        ("testToNotMatchesIfMatcherReturnsTrue", testToNotMatchesIfMatcherReturnsTrue),
        ("testToNotNegativeMatches", testToNotNegativeMatches),
        ("testToNotProvidesActualValueExpression", testToNotProvidesActualValueExpression),
        ("testToNotProvidesAMemoizedActualValueExpression", testToNotProvidesAMemoizedActualValueExpression),
        ("testToNotProvidesAMemoizedActualValueExpressionIsEvaluatedAtMatcherControl", testToNotProvidesAMemoizedActualValueExpressionIsEvaluatedAtMatcherControl),
        ("testToProvidesActualValueExpression", testToProvidesActualValueExpression),
        ("testToProvidesAMemoizedActualValueExpression", testToProvidesAMemoizedActualValueExpression),
        ("testToProvidesAMemoizedActualValueExpressionIsEvaluatedAtMatcherControl", testToProvidesAMemoizedActualValueExpressionIsEvaluatedAtMatcherControl),
        ("testUnexpectedErrorsThrownFails", testUnexpectedErrorsThrownFails),
    ]
}

extension ThrowAssertionTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ThrowAssertionTest = [
        ("testErrorThrown", testErrorThrown),
        ("testNegativeMatch", testNegativeMatch),
        ("testNegativeMessage", testNegativeMessage),
        ("testNonVoidClosure", testNonVoidClosure),
        ("testPositiveMatch", testPositiveMatch),
        ("testPositiveMessage", testPositiveMessage),
        ("testPostAssertionCodeNotRun", testPostAssertionCodeNotRun),
    ]
}

extension ThrowErrorTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ThrowErrorTest = [
        ("testNegativeMatches", testNegativeMatches),
        ("testNegativeMatchesDoNotCallClosureWithoutError", testNegativeMatchesDoNotCallClosureWithoutError),
        ("testNegativeMatchesWithClosure", testNegativeMatchesWithClosure),
        ("testNegativeNegatedMatches", testNegativeNegatedMatches),
        ("testNonVoidClosure", testNonVoidClosure),
        ("testPositiveMatches", testPositiveMatches),
        ("testPositiveMatchesWithClosures", testPositiveMatchesWithClosures),
        ("testPositiveNegatedMatches", testPositiveNegatedMatches),
    ]
}

extension ToSucceedTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ToSucceedTest = [
        ("testToSucceed", testToSucceed),
    ]
}

extension UserDescriptionTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UserDescriptionTest = [
        ("testNotToMatcher_CustomFailureMessage", testNotToMatcher_CustomFailureMessage),
        ("testToEventuallyMatch_CustomFailureMessage", testToEventuallyMatch_CustomFailureMessage),
        ("testToEventuallyNotMatch_CustomFailureMessage", testToEventuallyNotMatch_CustomFailureMessage),
        ("testToMatcher_CustomFailureMessage", testToMatcher_CustomFailureMessage),
        ("testToNotEventuallyMatch_CustomFailureMessage", testToNotEventuallyMatch_CustomFailureMessage),
        ("testToNotMatcher_CustomFailureMessage", testToNotMatcher_CustomFailureMessage),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AllPassTest.__allTests__AllPassTest),
        testCase(AsyncTest.__allTests__AsyncTest),
        testCase(BeAKindOfObjCTest.__allTests__BeAKindOfObjCTest),
        testCase(BeAKindOfSwiftTest.__allTests__BeAKindOfSwiftTest),
        testCase(BeAnInstanceOfTest.__allTests__BeAnInstanceOfTest),
        testCase(BeCloseToTest.__allTests__BeCloseToTest),
        testCase(BeEmptyTest.__allTests__BeEmptyTest),
        testCase(BeFalseTest.__allTests__BeFalseTest),
        testCase(BeFalsyTest.__allTests__BeFalsyTest),
        testCase(BeGreaterThanOrEqualToTest.__allTests__BeGreaterThanOrEqualToTest),
        testCase(BeGreaterThanTest.__allTests__BeGreaterThanTest),
        testCase(BeIdenticalToObjectTest.__allTests__BeIdenticalToObjectTest),
        testCase(BeIdenticalToTest.__allTests__BeIdenticalToTest),
        testCase(BeLessThanOrEqualToTest.__allTests__BeLessThanOrEqualToTest),
        testCase(BeLessThanTest.__allTests__BeLessThanTest),
        testCase(BeNilTest.__allTests__BeNilTest),
        testCase(BeTrueTest.__allTests__BeTrueTest),
        testCase(BeTruthyTest.__allTests__BeTruthyTest),
        testCase(BeVoidTest.__allTests__BeVoidTest),
        testCase(BeginWithTest.__allTests__BeginWithTest),
        testCase(ContainElementSatisfyingTest.__allTests__ContainElementSatisfyingTest),
        testCase(ContainTest.__allTests__ContainTest),
        testCase(ElementsEqualTest.__allTests__ElementsEqualTest),
        testCase(EndWithTest.__allTests__EndWithTest),
        testCase(EqualTest.__allTests__EqualTest),
        testCase(HaveCountTest.__allTests__HaveCountTest),
        testCase(MatchErrorTest.__allTests__MatchErrorTest),
        testCase(MatchTest.__allTests__MatchTest),
        testCase(PostNotificationTest.__allTests__PostNotificationTest),
        testCase(SatisfyAllOfTest.__allTests__SatisfyAllOfTest),
        testCase(SatisfyAnyOfTest.__allTests__SatisfyAnyOfTest),
        testCase(SynchronousTest.__allTests__SynchronousTest),
        testCase(ThrowAssertionTest.__allTests__ThrowAssertionTest),
        testCase(ThrowErrorTest.__allTests__ThrowErrorTest),
        testCase(ToSucceedTest.__allTests__ToSucceedTest),
        testCase(UserDescriptionTest.__allTests__UserDescriptionTest),
    ]
}
#endif
