#!/usr/bin/env sh

export DOCC_JSON_PRETTYPRINT="YES"

mkdir -p docs

swift package --allow-writing-to-directory docs \
    generate-documentation --target Nimble \
    --disable-indexing \
    --transform-for-static-hosting \
    --hosting-base-path 'https://quick.github.io/Nimble' \
    --output-path docs
