name: CI (SwiftPM)

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  swiftpm_darwin_monterey:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macos-12
    strategy:
      matrix:
        xcode: ["14.0.1", "14.1", "14.2"]
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app"
    steps:
      - uses: actions/checkout@v4
      - run: ./test swiftpm

  swiftpm_darwin_ventura:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macos-13
    strategy:
      matrix:
        xcode: ["14.3.1"]
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app"
    steps:
      - uses: actions/checkout@v4
      - run: ./test swiftpm

  swiftpm_linux:
    name: SwiftPM, Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - swift:5.7
          - swift:5.8
          # - swiftlang/swift:nightly
      fail-fast: false
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - run: swift build -Xswiftc -suppress-warnings
      - run: swift test -Xswiftc -suppress-warnings --enable-test-discovery

  swiftpm_windows:
    name: SwiftPM, Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.9-release
          tag: 5.9-RELEASE
      - name: Test Windows
        run: swift test -Xswiftc -suppress-warnings
