name: CI (SwiftPM)

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  swiftpm_darwin_sonoma:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macos-14
    strategy:
      matrix:
        xcode: ["16.1"]
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app"
    steps:
      - uses: actions/checkout@v4
      - run: ./test swiftpm

  swiftpm_darwin_sequoia:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macos-15
    strategy:
      matrix:
        xcode: ["16.3"]
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app"
    steps:
      - uses: actions/checkout@v4
      - run: ./test swiftpm

  swiftpm_linux:
    name: SwiftPM, Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - swift:6.0
          - swift:6.1
          - swift:6.2
          # - swiftlang/swift:nightly
      fail-fast: false
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - run: swift build -Xswiftc -suppress-warnings
      - run: swift test -Xswiftc -suppress-warnings --enable-test-discovery

  swiftpm_windows:
    name: SwiftPM, Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.2-release
          tag: 6.2-RELEASE
      - name: Test Windows
        run: swift test -Xswiftc -suppress-warnings
