name: CI (SwiftPM)

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  swiftpm_darwin:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macos-12
    strategy:
      matrix:
        xcode: ["14.0.1", "14.1", "14.2"]
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app"
    steps:
      - uses: actions/checkout@v3
      - run: ./test swiftpm

  swiftpm_linux:
    name: SwiftPM, Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - swift:5.7
          # - swiftlang/swift:nightly
      fail-fast: false
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
      - run: swift build -Xswiftc -suppress-warnings
      - run: swift test -Xswiftc -suppress-warnings --enable-test-discovery
