name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  cocoapods:
    name: CocoaPods Lint
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - run: sudo xcode-select -s '/Applications/Xcode_10.3.app'
    - run: bundle install --jobs=8
    - run: ./test podspec

  xcode:
    name: Xcode ${{ matrix.xcode }}
    runs-on: macOS-10.14
    strategy:
      matrix:
        xcode: [10.1, 10.3]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
    - run: ./test macos
    - run: ./test ios
    - run: ./test tvos

  swiftpm_darwin:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macOS-10.14
    strategy:
      matrix:
        xcode: [10.1, 10.3]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
    - run: ./test swiftpm

  swiftpm_linux:
    name: SwiftPM, Linux, Swift ${{ matrix.swift }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: [4.2.4, 5.0.3, 5.1-DEVELOPMENT-SNAPSHOT-2019-09-05-a]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - name: Run tests
      run: |
        eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        ./test swiftpm
      env:
        SWIFT_VERSION: ${{ matrix.swift }}
