name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  cocoapods:
    name: CocoaPods Lint
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - run: bundle install --jobs=8
    - run: ./test podspec

  xcode:
    name: Xcode ${{ matrix.xcode }} - ${{ matrix.platform }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [11, 11.1]
        platform: [macos, ios, tvos]
    steps:
    - uses: actions/checkout@v1
    - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
    - run: ./test ${{ matrix.platform }}

  swiftpm_darwin:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [11, 11.1]
    steps:
    - uses: actions/checkout@v1
    - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
    - run: ./test swiftpm
