name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  cocoapods:
    name: CocoaPods Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: bundle install
      - run: ./test podspec

  xcode:
    name: Xcode ${{ matrix.xcode }} - ${{ matrix.platform }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [12]
        platform: [macos, ios, tvos, macos_xcodespm, ios_xcodespm, tvos_xcodespm]
      fail-fast: false
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
      - uses: actions/checkout@v2
      - run: ./test ${{ matrix.platform }}

  swiftpm_darwin:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [12]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
      - uses: actions/checkout@v2
      - run: ./test swiftpm
